/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.mironovmike.kafkarest.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class GeneralMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1686175025972890380L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GeneralMessage\",\"namespace\":\"ru.mironovmike.kafkarest.schema\",\"fields\":[{\"name\":\"data\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GeneralMessage> ENCODER =
      new BinaryMessageEncoder<GeneralMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GeneralMessage> DECODER =
      new BinaryMessageDecoder<GeneralMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<GeneralMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<GeneralMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GeneralMessage>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this GeneralMessage to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a GeneralMessage from a ByteBuffer. */
  public static GeneralMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GeneralMessage() {}

  /**
   * All-args constructor.
   * @param data The new value for data
   */
  public GeneralMessage(java.lang.CharSequence data) {
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.lang.CharSequence getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.lang.CharSequence value) {
    this.data = value;
  }

  /**
   * Creates a new GeneralMessage RecordBuilder.
   * @return A new GeneralMessage RecordBuilder
   */
  public static ru.mironovmike.kafkarest.schema.GeneralMessage.Builder newBuilder() {
    return new ru.mironovmike.kafkarest.schema.GeneralMessage.Builder();
  }

  /**
   * Creates a new GeneralMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GeneralMessage RecordBuilder
   */
  public static ru.mironovmike.kafkarest.schema.GeneralMessage.Builder newBuilder(ru.mironovmike.kafkarest.schema.GeneralMessage.Builder other) {
    return new ru.mironovmike.kafkarest.schema.GeneralMessage.Builder(other);
  }

  /**
   * Creates a new GeneralMessage RecordBuilder by copying an existing GeneralMessage instance.
   * @param other The existing instance to copy.
   * @return A new GeneralMessage RecordBuilder
   */
  public static ru.mironovmike.kafkarest.schema.GeneralMessage.Builder newBuilder(ru.mironovmike.kafkarest.schema.GeneralMessage other) {
    return new ru.mironovmike.kafkarest.schema.GeneralMessage.Builder(other);
  }

  /**
   * RecordBuilder for GeneralMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GeneralMessage>
    implements org.apache.avro.data.RecordBuilder<GeneralMessage> {

    private java.lang.CharSequence data;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ru.mironovmike.kafkarest.schema.GeneralMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing GeneralMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(ru.mironovmike.kafkarest.schema.GeneralMessage other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.lang.CharSequence getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public ru.mironovmike.kafkarest.schema.GeneralMessage.Builder setData(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.data = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public ru.mironovmike.kafkarest.schema.GeneralMessage.Builder clearData() {
      data = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GeneralMessage build() {
      try {
        GeneralMessage record = new GeneralMessage();
        record.data = fieldSetFlags()[0] ? this.data : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GeneralMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<GeneralMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GeneralMessage>
    READER$ = (org.apache.avro.io.DatumReader<GeneralMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
